<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <StartupObject></StartupObject>
    <AssemblyVersion>0.12.7</AssemblyVersion>
    <PublishAot>False</PublishAot>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="Scripts\**\*.csx" />
	<Compile Remove="Scripts\**\Mai*.csx" />
	<None Update="Scripts\**\*.csx">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	 <None Include="Types\Core\Database.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CS-Script" Version="4.8.14" />
    <PackageReference Include="CZGL.SystemInfo" Version="2.2.0" />
    <PackageReference Include="DnsClient" Version="1.7.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.25.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.7" />
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
    <PackageReference Include="YamlDotNet" Version="15.1.4" />
    <PackageReference Include="ZXing.Net" Version="0.16.6" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.10" />
  </ItemGroup>

</Project>
